services:
  backend:
    image: ghcr.io/trevor-viljoen/tablo-web-backend:latest
    build: ./backend
    restart: unless-stopped
    volumes:
      - data:/data
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - "8000"
    networks:
      - internal

  frontend:
    image: ghcr.io/trevor-viljoen/tablo-web-frontend:latest
    build: ./frontend
    restart: unless-stopped
    ports:
      - "7070:80"
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:

volumes:
  data:
